/// A financial insight generated by the backend for a tracking period.
/// Read-only from the server; Home shows the "during" insights of the active
/// period. Mirrors the backend `insightResponse` object.
class Insight {
  const Insight({
    required this.id,
    required this.insightType,
    required this.calculationPhase,
    required this.severity,
    required this.title,
    required this.message,
    required this.createdAt,
    this.actionLabel,
    this.actionTarget,
    this.data,
    this.relatedCategoryId,
    this.relatedAccountId,
    this.relatedGoalId,
  });

  final String id;

  /// e.g. spending_pace | budget_warning | budget_exceeded | ant_expenses_early
  final String insightType;

  /// during | final
  final String calculationPhase;

  /// info | success | warning | critical
  final String severity;

  final String title;
  final String message;

  final String? actionLabel;
  final String? actionTarget;

  /// Per-type raw payload; shape depends on [insightType].
  final Map<String, dynamic>? data;

  final String? relatedCategoryId;
  final String? relatedAccountId;
  final String? relatedGoalId;

  final DateTime createdAt;

  factory Insight.fromJson(Map<String, dynamic> json) => Insight(
    id: json['id'] as String,
    insightType: json['insight_type'] as String,
    calculationPhase: json['calculation_phase'] as String,
    severity: json['severity'] as String,
    title: json['title'] as String,
    message: json['message'] as String,
    actionLabel: json['action_label'] as String?,
    actionTarget: json['action_target'] as String?,
    data: json['data'] as Map<String, dynamic>?,
    relatedCategoryId: json['related_category_id'] as String?,
    relatedAccountId: json['related_account_id'] as String?,
    relatedGoalId: json['related_goal_id'] as String?,
    createdAt: DateTime.parse(json['created_at'] as String),
  );
}
